apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qfmm8vowh-nodejs 
  janus-idp.io/tekton: qfmm8vowh-nodejs
  backstage.io/kubernetes-id: qfmm8vowh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qfmm8vowh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  